//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace suporteZ.cmd.cryptof.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Comando {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Comando() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("suporteZ.cmd.cryptof.Properties.Comando", typeof(Comando).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to determine the action: crypt or decrypt? (choose only one).
        /// </summary>
        internal static string msgConflitoCryptDecrypt {
            get {
                return ResourceManager.GetString("msgConflitoCryptDecrypt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to determine the source of the password: informed value or clipboard? (choose only one).
        /// </summary>
        internal static string msgConflitoSenhaClipboard {
            get {
                return ResourceManager.GetString("msgConflitoSenhaClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The crypto command provides functions in the context\nof encryption for files and folders..
        /// </summary>
        internal static string msgDescricao {
            get {
                return ResourceManager.GetString("msgDescricao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must choice one of the action arguments: {0} or {1}.
        /// </summary>
        internal static string msgNecessarioIndicarAcao {
            get {
                return ResourceManager.GetString("msgNecessarioIndicarAcao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must choice one of the output arguments: {0} or {1}.
        /// </summary>
        internal static string msgNecessarioIndicarSaida {
            get {
                return ResourceManager.GetString("msgNecessarioIndicarSaida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No input file or folder was informed..
        /// </summary>
        internal static string msgNenhumArquivoDeEntrada {
            get {
                return ResourceManager.GetString("msgNenhumArquivoDeEntrada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The amount of file or folder output must be equal to the input..
        /// </summary>
        internal static string msgQuantidadeDeArquivosDeEntradaESaidaDevemSerIguais {
            get {
                return ResourceManager.GetString("msgQuantidadeDeArquivosDeEntradaESaidaDevemSerIguais", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Symmetric encryption algorithm.\nValid options for VALUE:\n  DES       - uses  64-bit key\n  RC2       - uses 128-bit key\n  TripleDES - uses 192-bit key\n  Rijndael  - uses 256-bit key (default).
        /// </summary>
        internal static string optionAlgoritmoDeCriptografia {
            get {
                return ResourceManager.GetString("optionAlgoritmoDeCriptografia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File or folder input.
        /// </summary>
        internal static string optionArquivoEntrada {
            get {
                return ResourceManager.GetString("optionArquivoEntrada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File or folder output.
        /// </summary>
        internal static string optionArquivoSaida {
            get {
                return ResourceManager.GetString("optionArquivoSaida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action of encrypting.
        /// </summary>
        internal static string optionCriptografar {
            get {
                return ResourceManager.GetString("optionCriptografar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action of decrypt.
        /// </summary>
        internal static string optionDescriptografar {
            get {
                return ResourceManager.GetString("optionDescriptografar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Integrate this tool with Windows. View encryption option when right clicking on files and folders via Explorer..
        /// </summary>
        internal static string optionIntegrarComWindowsAtivado {
            get {
                return ResourceManager.GetString("optionIntegrarComWindowsAtivado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable Windows integration..
        /// </summary>
        internal static string optionIntegrarComWindowsDesativado {
            get {
                return ResourceManager.GetString("optionIntegrarComWindowsDesativado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use graphical interface (GUI).
        /// </summary>
        internal static string optionInterfaceGrafica {
            get {
                return ResourceManager.GetString("optionInterfaceGrafica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Causes the result of the encryption process overwrite the original file or folder..
        /// </summary>
        internal static string optionSaidaNoMesmoArquivoDeEntrada {
            get {
                return ResourceManager.GetString("optionSaidaNoMesmoArquivoDeEntrada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password applied in the encryption process.
        /// </summary>
        internal static string optionSenha {
            get {
                return ResourceManager.GetString("optionSenha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get from clipboard the password applied in the encryption process.
        /// </summary>
        internal static string optionSenhaComoClipboard {
            get {
                return ResourceManager.GetString("optionSenhaComoClipboard", resourceCulture);
            }
        }
    }
}
