//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace suporteZ.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Comando {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Comando() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("suporteZ.Properties.Comando", typeof(Comando).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {NomeDoAplicativo} (version {VersaoDoAplicativo}).
        /// </summary>
        internal static string ajudaCabecalho01 {
            get {
                return ResourceManager.GetString("ajudaCabecalho01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General purpose tools.
        /// </summary>
        internal static string ajudaCabecalho02 {
            get {
                return ResourceManager.GetString("ajudaCabecalho02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sergio@cabral.br.com.
        /// </summary>
        internal static string ajudaCabecalho03 {
            get {
                return ResourceManager.GetString("ajudaCabecalho03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ajudaCabecalho04 {
            get {
                return ResourceManager.GetString("ajudaCabecalho04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Syntax:.
        /// </summary>
        internal static string ajudaLinha04 {
            get {
                return ResourceManager.GetString("ajudaLinha04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   {NomeDoExecutavel} [language] &lt;command&gt;.
        /// </summary>
        internal static string ajudaLinha05 {
            get {
                return ResourceManager.GetString("ajudaLinha05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ajudaLinha06 {
            get {
                return ResourceManager.GetString("ajudaLinha06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Example:.
        /// </summary>
        internal static string ajudaLinha07 {
            get {
                return ResourceManager.GetString("ajudaLinha07", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   {NomeDoExecutavel} crypto /?.
        /// </summary>
        internal static string ajudaLinha08 {
            get {
                return ResourceManager.GetString("ajudaLinha08", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   {NomeDoExecutavel} pt-BR crypto /?.
        /// </summary>
        internal static string ajudaLinha09 {
            get {
                return ResourceManager.GetString("ajudaLinha09", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ajudaLinha10 {
            get {
                return ResourceManager.GetString("ajudaLinha10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Languages:.
        /// </summary>
        internal static string ajudaLinha11 {
            get {
                return ResourceManager.GetString("ajudaLinha11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   pt-BR.
        /// </summary>
        internal static string ajudaLinha12 {
            get {
                return ResourceManager.GetString("ajudaLinha12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   en-US.
        /// </summary>
        internal static string ajudaLinha13 {
            get {
                return ResourceManager.GetString("ajudaLinha13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ajudaLinha14 {
            get {
                return ResourceManager.GetString("ajudaLinha14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * The executable can be renamed to embed language;.
        /// </summary>
        internal static string ajudaLinha15 {
            get {
                return ResourceManager.GetString("ajudaLinha15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to for example: &quot;{ParteInicialDoNomeDoExecutavel}.pt-BR.exe&quot;.
        /// </summary>
        internal static string ajudaLinha16 {
            get {
                return ResourceManager.GetString("ajudaLinha16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ajudaLinha17 {
            get {
                return ResourceManager.GetString("ajudaLinha17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available commands:.
        /// </summary>
        internal static string ajudaLinha18 {
            get {
                return ResourceManager.GetString("ajudaLinha18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {ComandosDisponiveis}.
        /// </summary>
        internal static string ajudaLinha19 {
            get {
                return ResourceManager.GetString("ajudaLinha19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ex&amp;it.
        /// </summary>
        internal static string formBase_menuItem_Aplicativo_Sair {
            get {
                return ResourceManager.GetString("formBase_menuItem_Aplicativo_Sair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ab&amp;out.
        /// </summary>
        internal static string formBase_menuItem_Aplicativo_Sobre {
            get {
                return ResourceManager.GetString("formBase_menuItem_Aplicativo_Sobre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Minimize to system tray.
        /// </summary>
        internal static string formBase_menuItem_Aplicativo_Tray {
            get {
                return ResourceManager.GetString("formBase_menuItem_Aplicativo_Tray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loaded files:\n* {0}\n* {1}.
        /// </summary>
        internal static string formBase_textBoxTexto_ArquivosCarregados {
            get {
                return ResourceManager.GetString("formBase_textBoxTexto_ArquivosCarregados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command: {0} (version {1}).
        /// </summary>
        internal static string formBase_textBoxTexto_Comando {
            get {
                return ResourceManager.GetString("formBase_textBoxTexto_Comando", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command line:\n  {0}.
        /// </summary>
        internal static string formBase_textBoxTexto_LinhaDeComando {
            get {
                return ResourceManager.GetString("formBase_textBoxTexto_LinhaDeComando", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string formSobre_ButtonFechar {
            get {
                return ResourceManager.GetString("formSobre_ButtonFechar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help for the command: {0} (version {1}).
        /// </summary>
        internal static string msgAjudaParaComando {
            get {
                return ResourceManager.GetString("msgAjudaParaComando", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The argument &quot;{0}&quot; must be used alone..
        /// </summary>
        internal static string msgArgumentoDeveSerSozinho {
            get {
                return ResourceManager.GetString("msgArgumentoDeveSerSozinho", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One or more arguments are invalid: {0}.
        /// </summary>
        internal static string msgArgumentosInvalidos {
            get {
                return ResourceManager.GetString("msgArgumentosInvalidos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The compilation of the library ({0}) is older than the executable ({1})..
        /// </summary>
        internal static string msgBibliotecaObsoleta {
            get {
                return ResourceManager.GetString("msgBibliotecaObsoleta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error with command &quot;{0}&quot; library &quot;{1}&quot;..
        /// </summary>
        internal static string msgComandoComBibliotecaInvalida {
            get {
                return ResourceManager.GetString("msgComandoComBibliotecaInvalida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To view the help, type: {0} {1} /?.
        /// </summary>
        internal static string msgConsulteAAjuda {
            get {
                return ResourceManager.GetString("msgConsulteAAjuda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not supported duplicity for the argument: {0}.
        /// </summary>
        internal static string msgDuplicidadeDeArgumento {
            get {
                return ResourceManager.GetString("msgDuplicidadeDeArgumento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR UNKNOWN:.
        /// </summary>
        internal static string msgErroDesconhecido {
            get {
                return ResourceManager.GetString("msgErroDesconhecido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SYNTAX ERROR:.
        /// </summary>
        internal static string msgErroDeSintaxe {
            get {
                return ResourceManager.GetString("msgErroDeSintaxe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR:.
        /// </summary>
        internal static string msgErroDoComando {
            get {
                return ResourceManager.GetString("msgErroDoComando", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No command was found..
        /// </summary>
        internal static string msgNenhumComandoDisponivel {
            get {
                return ResourceManager.GetString("msgNenhumComandoDisponivel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help on using this command..
        /// </summary>
        internal static string optionAjuda {
            get {
                return ResourceManager.GetString("optionAjuda", resourceCulture);
            }
        }
    }
}
