//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace suporteZ.cmd.crypto.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Comando {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Comando() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("suporteZ.cmd.crypto.Properties.Comando", typeof(Comando).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Performs the action...\neither encryption or decryption..
        /// </summary>
        internal static string formPrincipal_buttonAcao_Hint {
            get {
                return ResourceManager.GetString("formPrincipal_buttonAcao_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When activated performs the process\nof encryption/decryption automatically.\n\nWhen disabled is necessary to activate\nthe button to start the process of\nencryption/decryption..
        /// </summary>
        internal static string formPrincipal_checkBoxAcaoAutomatico_Hint {
            get {
                return ResourceManager.GetString("formPrincipal_checkBoxAcaoAutomatico_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Password.
        /// </summary>
        internal static string formPrincipal_labelSenha {
            get {
                return ResourceManager.GetString("formPrincipal_labelSenha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Input value.
        /// </summary>
        internal static string formPrincipal_labelValorEntrada {
            get {
                return ResourceManager.GetString("formPrincipal_labelValorEntrada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Output value.
        /// </summary>
        internal static string formPrincipal_labelValorSaida {
            get {
                return ResourceManager.GetString("formPrincipal_labelValorSaida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encryption algorithm.
        /// </summary>
        internal static string formPrincipal_menuItem_Biblioteca_Algoritmo {
            get {
                return ResourceManager.GetString("formPrincipal_menuItem_Biblioteca_Algoritmo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send result to &amp;clipboard.
        /// </summary>
        internal static string formPrincipal_menuItem_Biblioteca_Clipboard {
            get {
                return ResourceManager.GetString("formPrincipal_menuItem_Biblioteca_Clipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Binds the value of the password to clipboard.
        /// </summary>
        internal static string formPrincipal_menuItem_Biblioteca_ClipboardControlVPassword {
            get {
                return ResourceManager.GetString("formPrincipal_menuItem_Biblioteca_ClipboardControlVPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Binds the value of the input text to the clipboard.
        /// </summary>
        internal static string formPrincipal_menuItem_Biblioteca_ClipboardControlVValue {
            get {
                return ResourceManager.GetString("formPrincipal_menuItem_Biblioteca_ClipboardControlVValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not display the &amp;result.
        /// </summary>
        internal static string formPrincipal_menuItem_Biblioteca_Silent {
            get {
                return ResourceManager.GetString("formPrincipal_menuItem_Biblioteca_Silent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter here the password used\nto encrypt/decrypt the text..
        /// </summary>
        internal static string formPrincipal_panelIconePassword_Hint {
            get {
                return ResourceManager.GetString("formPrincipal_panelIconePassword_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter here the text to\nbe encrypted/decrypted..
        /// </summary>
        internal static string formPrincipal_panelIconeValorEntrada_Hint {
            get {
                return ResourceManager.GetString("formPrincipal_panelIconeValorEntrada_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here the result of the\nencryption/decryption\nprocess will be presented.\n\nThis just goes blank when\nattempting decryption fails\nbecause the text was not encrypted..
        /// </summary>
        internal static string formPrincipal_panelIconeValorSaida_Hint {
            get {
                return ResourceManager.GetString("formPrincipal_panelIconeValorSaida_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Encrypt.
        /// </summary>
        internal static string formPrincipal_radioButtonCrypt {
            get {
                return ResourceManager.GetString("formPrincipal_radioButtonCrypt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable this to encrypt the entered text.\n\nEven when no text is entered,\nan empty value will also be encrypted..
        /// </summary>
        internal static string formPrincipal_radioButtonCrypt_Hint {
            get {
                return ResourceManager.GetString("formPrincipal_radioButtonCrypt_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable this to decrypt the entered text.\n\nThe operation will be performed only\nif the entered text is encrypted..
        /// </summary>
        internal static string formPrincipal_radioButtonDecrypt_Hint {
            get {
                return ResourceManager.GetString("formPrincipal_radioButtonDecrypt_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Decrypt.
        /// </summary>
        internal static string formPrincipal_radioButtonDescrypt {
            get {
                return ResourceManager.GetString("formPrincipal_radioButtonDescrypt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid encryption algorithm: {0}.
        /// </summary>
        internal static string msgAlgoritmoInvalido {
            get {
                return ResourceManager.GetString("msgAlgoritmoInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to determine the action: crypt or decrypt? (choose only one).
        /// </summary>
        internal static string msgConflitoCryptDecrypt {
            get {
                return ResourceManager.GetString("msgConflitoCryptDecrypt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to determine the source of the password: informed value or clipboard? (choose only one).
        /// </summary>
        internal static string msgConflitoSenhaClipboard {
            get {
                return ResourceManager.GetString("msgConflitoSenhaClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to determine the soruce of the text: informed value or clipboard? (choose only one).
        /// </summary>
        internal static string msgConflitoValorClipboard {
            get {
                return ResourceManager.GetString("msgConflitoValorClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The crypto command provides functions in the context\nof encryption for text strings..
        /// </summary>
        internal static string msgDescricao {
            get {
                return ResourceManager.GetString("msgDescricao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The text was not an encrypted value. Operation canceled..
        /// </summary>
        internal static string msgTextoNaoEstavaCriptografado {
            get {
                return ResourceManager.GetString("msgTextoNaoEstavaCriptografado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Symmetric encryption algorithm.\nValid options for VALUE:\n  DES       - uses  64-bit key\n  RC2       - uses 128-bit key\n  TripleDES - uses 192-bit key\n  Rijndael  - uses 256-bit key (default).
        /// </summary>
        internal static string optionAlgoritmoDeCriptografia {
            get {
                return ResourceManager.GetString("optionAlgoritmoDeCriptografia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action of encrypting (default).
        /// </summary>
        internal static string optionCriptografar {
            get {
                return ResourceManager.GetString("optionCriptografar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action of decrypt.
        /// </summary>
        internal static string optionDescriptografar {
            get {
                return ResourceManager.GetString("optionDescriptografar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sends the result of encryption process to the clipboard.
        /// </summary>
        internal static string optionEnviarResultadoParaClipboard {
            get {
                return ResourceManager.GetString("optionEnviarResultadoParaClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use graphical interface (GUI).
        /// </summary>
        internal static string optionInterfaceGrafica {
            get {
                return ResourceManager.GetString("optionInterfaceGrafica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Silent mode does not display the result of the encryption process.
        /// </summary>
        internal static string optionModoSilencioso {
            get {
                return ResourceManager.GetString("optionModoSilencioso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password applied in the encryption process.
        /// </summary>
        internal static string optionSenha {
            get {
                return ResourceManager.GetString("optionSenha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get from clipboard the password applied in the encryption process.
        /// </summary>
        internal static string optionSenhaComoClipboard {
            get {
                return ResourceManager.GetString("optionSenhaComoClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get from clipboard the text to be manipulated.
        /// </summary>
        internal static string optionTextoComoClipboard {
            get {
                return ResourceManager.GetString("optionTextoComoClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text to be manipulated.
        /// </summary>
        internal static string optionTextoParaManipular {
            get {
                return ResourceManager.GetString("optionTextoParaManipular", resourceCulture);
            }
        }
    }
}
